name: upload_artifact

on:
  push:
    tags:
      - "v*"

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.21.0"

      - name: Build
        run: |
          echo 'Build linux amd 64'
          env CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build
          chmod +x ./uuid-clipboard

          echo 'Build linux arm 32'
          env CGO_ENABLED=1 GOOS=linux GOARCH=arm go build -o uuid-clipboard-arm32
          chmod +x ./uuid-clipboard-arm32

          echo 'Build linux arm 64'
          env CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -o uuid-clipboard-arm64
          chmod +x ./uuid-clipboard-arm64

          echo 'Build windows amd 64'
          env CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build
          chmod +x ./uuid-clipboard.exe

          echo 'Build mac apple silicon'
          env CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -o uuid-clipboard-apple-silicon
          chmod +x ./uuid-clipboard-apple-silicon

      - name: Set GitHub user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "uuid-clipboard*"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          omitBody: true
          omitBodyDuringUpdate: true
          omitName: true
          omitNameDuringUpdate: true
