name: upload_artifact

on:
   push:
        tags:
            - "v*"

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        echo 'Build linux amd 64'
        env GOOS=linux GOARCH=amd64 go build -o ./linux-amd64/
        chmod +x ./linux-amd64/uuid-clipboard

        echo 'Build linux arm 32'
        env GOOS=linux GOARCH=arm go build -o ./linux-arm32/
        chmod +x ./linux-arm32/uuid-clipboard-arm32

        echo 'Build linux arm 64'
        env GOOS=linux GOARCH=arm64 go build -o ./linux-arm64/
        chmod +x ./linux-arm64/uuid-clipboard

        echo 'Build windows amd 64'
        env GOOS=windows GOARCH=amd64 go build -o ./windows/
        chmod +x ./windows/uuid-clipboard.exe

        echo 'Build mac apple silicon'
        env GOOS=darwin GOARCH=arm64 go build -o ./apple-silicon/
        chmod +x ./apple-silicon/uuid-clipboard

    - name: Set GitHub user
      run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
    - name: Publish GitHub Release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "linux-amd64,linux-arm32,linux-arm64,windows,apple-silicon"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          omitBody: true
          omitBodyDuringUpdate: true
          omitName: true
          omitNameDuringUpdate: true
